openapi: 3.1.0
info:
  title: Manifest API
  version: 1.0.0
  description: ''
paths:
  /api/v1/datacenters:
    get:
      operationId: manifest_api_v1_list_datacenters
      summary: List Datacenters
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DatacenterSchema'
                title: Response
                type: array
    post:
      operationId: manifest_api_v1_create_datacenter
      summary: Create Datacenter
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatacenterSchema'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatacenterCreateSchema'
        required: true
  /api/v1/datacenters/{datacenter_id}:
    get:
      operationId: manifest_api_v1_get_datacenter
      summary: Get Datacenter
      parameters:
        - in: path
          name: datacenter_id
          schema:
            title: Datacenter Id
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatacenterSchema'
  /api/v1/racks:
    get:
      operationId: manifest_api_v1_list_racks
      summary: List Racks
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/RackSchema'
                title: Response
                type: array
    post:
      operationId: manifest_api_v1_create_rack
      summary: Create Rack
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RackSchema'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RackCreateSchema'
        required: true
  /api/v1/racks/{rack_id}:
    get:
      operationId: manifest_api_v1_get_rack
      summary: Get Rack
      parameters:
        - in: path
          name: rack_id
          schema:
            title: Rack Id
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RackSchema'
components:
  schemas:
    DatacenterSchema:
      properties:
        id:
          anyOf:
            - type: integer
            - type: 'null'
          title: ID
        name:
          maxLength: 100
          title: Name
          type: string
        location:
          maxLength: 200
          title: Location
          type: string
      required:
        - name
        - location
      title: DatacenterSchema
      type: object
    DatacenterCreateSchema:
      properties:
        name:
          maxLength: 100
          title: Name
          type: string
        location:
          maxLength: 200
          title: Location
          type: string
      required:
        - name
        - location
      title: DatacenterCreateSchema
      type: object
    RackSchema:
      properties:
        id:
          anyOf:
            - type: integer
            - type: 'null'
          title: ID
        datacenter:
          title: Datacenter
          type: integer
        name:
          maxLength: 50
          title: Name
          type: string
        position:
          anyOf:
            - maxLength: 50
              type: string
            - type: 'null'
          title: Position
      required:
        - datacenter
        - name
      title: RackSchema
      type: object
    RackCreateSchema:
      properties:
        name:
          maxLength: 50
          title: Name
          type: string
        position:
          anyOf:
            - maxLength: 50
              type: string
            - type: 'null'
          title: Position
        datacenter_id:
          title: Datacenter
          type: integer
      required:
        - name
        - datacenter_id
      title: RackCreateSchema
      type: object
servers: []
