openapi: 3.1.0
info:
  title: Manifest API
  version: 1.0.0
  description: ''
paths:
  /api/v1/datacenter:
    post:
      operationId: manifest_api_v1_create_datacenter
      summary: Create Datacenter
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datacenter'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Datacenter'
        required: true
      x-speakeasy-entity-operation: Datacenter#create
  /api/v1/datacenter/{datacenter_id}:
    get:
      operationId: manifest_api_v1_get_datacenter
      summary: Get Datacenter
      parameters:
        - in: path
          name: datacenter_id
          schema:
            title: Datacenter Id
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datacenter'
      x-speakeasy-entity-operation: Datacenter#read
    post:
      operationId: manifest_api_v1_update_datacenter
      summary: Update Datacenter
      parameters:
        - in: path
          name: datacenter_id
          schema:
            title: Datacenter Id
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datacenter'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Datacenter'
        required: true
      x-speakeasy-entity-operation: Datacenter#update
    delete:
      operationId: manifest_api_v1_delete_datacenter
      summary: Delete Datacenter
      parameters:
        - in: path
          name: datacenter_id
          schema:
            title: Datacenter Id
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Datacenter'
      x-speakeasy-entity-operation: Datacenter#delete
components:
  schemas:
    Datacenter:
      properties:
        id:
          anyOf:
            - type: integer
            - type: 'null'
          title: ID
        name:
          maxLength: 100
          title: Name
          type: string
        location:
          maxLength: 200
          title: Location
          type: string
      required:
        - name
        - location
      title: Datacenter
      type: object
      x-speakeasy-entity: Datacenter
servers: []
